"
" GENERAL
"

set nocompatible
scriptencoding utf-8
set encoding=utf-8


"
" PLUGINS
"

call plug#begin('~/.vim/plugged')
source $HOME/.vimrc_plugins
call plug#end()


"
" FILETYPES
"

autocmd FileType gitcommit setlocal formatoptions+=t textwidth=72
autocmd FileType make setlocal noexpandtab


"
" INDENTATION
"

" tabs vs spaces
set expandtab " insert space characters whenever the tab key is pressed
set tabstop=4 " number of space characters that will be inserted when the tab key is pressed
set shiftwidth=4 " number of space characters inserted for indentation
set softtabstop=4 " makes the backspace key treat four spaces like a tab
set backspace=indent,eol,start
filetype plugin indent on
vnoremap < <gv
vnoremap > >gv


"
" LINENUMBERS
"

set number
set relativenumber


"
" APPEARANCE
"

syntax on

"" display whitespace
" get list of digraphs with :dig
" to enter digraphs hit ctrl-k followed
" by the character combination in insert mode
" digraphs used:
"  tab digraphs: `dr` and a simple dash
"  trail digraphs: `.M`
set list
set listchars=tab:┌-,trail:·

set background=light

