test -f "${HOME}/.profile" &&
  source "${HOME}/.profile"

test -f "${HOME}/.bashrc" &&
  source "${HOME}/.bashrc"

# don't put duplicate lines or lines starting with space in the history
export HISTCONTROL=ignoreboth

test -z "$DISPLAY" &&
  test $(tty) = "/dev/tty1" &&
  exec startx
