#xrdb $HOME/.Xresources

# set layout to german, eliminate deadkeys, remap caps to escape and blow up caps for good
setxkbmap -layout de -variant nodeadkeys -option "caps:escape"

#tpset() {
# xinput set-prop "TPPS/2 IBM TrackPoint" "$@";
#}
#
#tpset "Evdev Wheel Emulation" 1
#tpset "Evdev Wheel Emulation Button" 2
#tpset "Evdev Wheel Emulation Timeout" 200
#tpset "Evdev Wheel Emulation Axes" 6 7 4 5
#tpset "Device Accel Constant Deceleration" 0.95

xsetroot -cursor_name left_ptr
xrdb -merge "${HOME}/.Xresources"
exec openbox-session
#exec xmonad
